export const RESET_FILTERS = 'expats/RESET_FILTERS';
export const SET_FILTER = 'expats/SET_FILTER';
export const ACTIVATE_DROPDOWN_FILTERS = 'expats/ACTIVATE_DROPDOWN_FILTERS';
export const DEACTIVATE_DROPDOWN_FILTERS = 'expats/DEACTIVATE_DROPDOWN_FILTERS';
export const SHOW_MORE_OPINIONS = 'expats/SHOW_MORE_OPINIONS';
